version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    working_directory: ~/spring-mvc-test-utils
    docker:
      - image: circleci/openjdk:11

    steps:
      - checkout
      - restore_cache:
          key: spring-mvc-test-utils-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: spring-mvc-test-utils-{{ checksum "pom.xml" }}
      - run: mvn verify
      - store_test_results:
          path: target/surefire-reports
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml